[package]
name = "spaceship"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = { version = "0.15.3", features = ["multi_threaded", "serialize"] }
eframe = "0.31.1"
egui = "0.31.1"
egui_plot = "0.32.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
